beautiful
lui-lasercat7/lui-lasercat7.github.io pull request #1
Opened 2017-01-12 19:13 UTC by lui-lasercat7

Lui's Änderungen

2017-01-17 11:08 UTC, codingjoe requested changes
😘

2017-01-17 11:08 UTC, codingjoe commented on Lebenslauf.html
> +            <th style="text-align:center;">Zeitraum</th>
You should remove all inline styles in favor of proper styles by tag or class.

2017-01-17 11:08 UTC, codingjoe commented on Lebenslauf.html
> +        </tr>
`HTML` is missing 😉

2017-01-17 11:08 UTC, codingjoe commented on Lebenslauf.html
> +            <td>Allgemeine Hochschulreife, <a href="https://www.wolkenberg-gymnasium.de/">Wolkenberg Gymnasium Michendorf</a></td>
If you don't want people to leave your CV when they click the link, but rather want to page to open in a new tab, you should have a look at the [`target`](http://www.w3schools.com/tags/att_a_target.asp)-attribute.

2017-01-17 11:08 UTC, codingjoe commented on Lebenslauf.html
> +            <td><i>2014-heute</i></td>
There are multiple dashes. The one uses between dates is usually: `&ndash;`. [More here...](https://de.wikipedia.org/wiki/Halbgeviertstrich#Bis-Strich)

2017-01-17 11:08 UTC, codingjoe commented on Lebenslauf.html
> +    <p>E-Mail: luisemaron@googlemail.com</p>
You could use a [description list](http://www.w3schools.com/tags/tag_dl.asp) or `<dl>` tag here.

2017-01-17 11:08 UTC, codingjoe commented on Lebenslauf.html
> +    <img src="Passfoto.jpg" width="150" height="224">
You don't need to specify `width` & `height`. You do need to specify an `alt`-attribute tho. The `alt`-attribute is an alternative text, should the image not been displayed. For accessibility reason or due to loading issues.

2017-01-17 11:08 UTC, codingjoe commented on Lebenslauf.html
> +    <hr>
You can use horizontal lines, but if there are merely used as an under line you can use a [`border`](http://www.w3schools.com/css/css_border.asp).

2017-01-19 10:15 UTC, lui-lasercat7 commented on Lebenslauf.html
> +    <p>E-Mail: luisemaron@googlemail.com</p>
Verstehe nicht, warum hier eine description list Sinn machen würde? 
Dann wäre doch alles "verschoben" und nicht untereinander geordnet?!

2017-01-19 10:25 UTC, lui-lasercat7 commented on Lebenslauf.html
> +            <th style="text-align:center;">Zeitraum</th>
? :(

2017-01-19 16:27 UTC, codingjoe commented on Lebenslauf.html
> +    <p>E-Mail: luisemaron@googlemail.com</p>
```html
<dl>
   ...
  <dt>E-Mail:</dt>
  <dd>luisemaron@gmail.com</dd>
  ...
</dl>
```

2017-01-19 16:28 UTC, codingjoe commented on Lebenslauf.html
> +            <th style="text-align:center;">Zeitraum</th>
Just use the `<style>`-section in the header. It's considered a cleaner code style.

2017-01-20 13:16 UTC, codingjoe requested changes

2017-01-20 13:16 UTC, codingjoe commented on Lebenslauf.html
> +<style>
`style` tag only belongs in the `head` section

2017-01-20 13:16 UTC, codingjoe commented on Lebenslauf.html
> +<style>
same here

2017-01-20 13:19 UTC, codingjoe commented
@lui-lasercat7 sehr gut, weiter so 😘

2017-01-20 15:01 UTC, lui-lasercat7 commented
Danke <3

Ich mach aber Schluss für heute, reicht mit ausprobieren

2017-01-20 14:19 GMT+01:00 Johannes Hoppe <notifications@github.com>:

> @lui-lasercat7 <https://github.com/lui-lasercat7> sehr gut, weiter so 😘
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lui-lasercat7/lui-lasercat7.github.io/pull/1#issuecomment-274070276>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AX0aRVxjI5tul5ErOlk5oneFx1huzroxks5rULRqgaJpZM4LiH6m>
> .
>

2017-01-25 10:16 UTC, codingjoe requested changes

2017-01-25 10:16 UTC, codingjoe commented on Lebenslauf.html
> +            font-family: "Slabo+27px", serif;
??? Das kann nicht funktionieren. Außerdem ist Slabo nicht geladen, siehe Zeile 5.

2017-01-25 10:33 UTC, lui-lasercat7 commented
Habs ja auch wieder auf Lato geändert

Am 25.01.2017 11:16 schrieb "Johannes Hoppe" <notifications@github.com>:

> *@codingjoe* requested changes on this pull request.
> ------------------------------
>
> In Lebenslauf.html
> <https://github.com/lui-lasercat7/lui-lasercat7.github.io/pull/1#pullrequestreview-18364703>
> :
>
> > @@ -8,7 +8,7 @@
>          body {
>              margin: 0;
>              box-sizing: border-box;
> -            font-family: "Ubuntu", sans-serif;
> +            font-family: "Slabo+27px", serif;
>
> ??? Das kann nicht funktionieren. Außerdem ist Slabo nicht geladen, siehe
> Zeile 5.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lui-lasercat7/lui-lasercat7.github.io/pull/1#pullrequestreview-18364703>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AX0aRQ68jF4mdDmHA9e493x3bMWDcPfwks5rVyDpgaJpZM4LiH6m>
> .
>

2017-01-25 11:02 UTC, codingjoe approved these changes

2017-01-25 11:02 UTC, codingjoe commented on Lebenslauf.html
> +        <img src="Passfoto_2.jpg" alt="Luise Maron" id="headshot">
Wenn du Fotos machen lässt, dann würde ich auch eines mit Geschlossenem Haar machen. Das wirkt strenger, das ist nicht schlecht.

2017-02-05 16:52 UTC, merged